/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Swing;

/**
 *
 * @author cifuentes0903
 */
public class Formulariogas extends javax.swing.JFrame {

    /**
     * Creates new form Formulariogas
     */
    
   Double Num1,Num2;
    public Formulariogas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tnum1 = new javax.swing.JTextField();
        Tnum2 = new javax.swing.JTextField();
        TResultado = new javax.swing.JLabel();
        Bsuma = new javax.swing.JButton();
        Titulo2 = new javax.swing.JLabel();
        Titulo1 = new javax.swing.JLabel();
        Bresta = new javax.swing.JButton();
        Blimpiar = new javax.swing.JButton();
        Bmulti = new javax.swing.JButton();
        Bdivi1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tnum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tnum1ActionPerformed(evt);
            }
        });

        TResultado.setText("Resultado");

        Bsuma.setText("Suma");
        Bsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsumaActionPerformed(evt);
            }
        });

        Titulo2.setText("Digite el Num2");

        Titulo1.setText("Digite el Num1");
        Titulo1.setName("Titulo1"); // NOI18N

        Bresta.setText("Resta");
        Bresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrestaActionPerformed(evt);
            }
        });

        Blimpiar.setText("Limpiar");
        Blimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlimpiarActionPerformed(evt);
            }
        });

        Bmulti.setText("Multiplicación");
        Bmulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BmultiActionPerformed(evt);
            }
        });

        Bdivi1.setText("División");
        Bdivi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bdivi1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Bmulti)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Bsuma, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Titulo2)
                                    .addComponent(Titulo1)))
                            .addComponent(Bresta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TResultado)
                            .addComponent(Tnum2, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(Tnum1))
                        .addGap(46, 46, 46))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Blimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(Bdivi1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(279, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Titulo1)
                    .addComponent(Tnum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Titulo2)
                    .addComponent(Tnum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(Bsuma)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TResultado)
                    .addComponent(Bresta))
                .addGap(18, 18, 18)
                .addComponent(Blimpiar)
                .addGap(18, 18, 18)
                .addComponent(Bmulti)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(226, Short.MAX_VALUE)
                    .addComponent(Bdivi1)
                    .addGap(51, 51, 51)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tnum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tnum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tnum1ActionPerformed

    private void BsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsumaActionPerformed
/*        Double valor1;
        Double valor2;// TODO add your handling code here:
        Double sumar;

        valor1=Double.parseDouble(this.Tnum1.getText());
        valor2=Double.parseDouble(this.Tnum2.getText());
        sumar = valor1+valor2;

        String resultado = String.valueOf(sumar);

        TResultado.setText(String.valueOf(resultado));*/
    Gas objeto = new Gas();
    objeto.capturar(Num1, Num2);
    Num1 = Double.parseDouble(Tnum1.getText());
    Num2 = Double.parseDouble(Tnum2.getText());
    
    double Suma = objeto.sumar(Num1,Num2);
    
   // objeto.Sumar();
    
  // String total= String.valueOf();
   //total = String.valueOf(objeto);
   TResultado.setText(String.valueOf(Suma));
   
   
    

    }//GEN-LAST:event_BsumaActionPerformed

    private void BrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrestaActionPerformed
        Gas objeto = new Gas();
    objeto.capturar(Num1, Num2);
    Num1 = Double.parseDouble(Tnum1.getText());
    Num2 = Double.parseDouble(Tnum2.getText());
    
    double resta = objeto.resta(Num1,Num2);
    TResultado.setText(String.valueOf(resta));
    
    }//GEN-LAST:event_BrestaActionPerformed

    private void BlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlimpiarActionPerformed
            Tnum1.setText("");
            Tnum2.setText("");
            TResultado.setText("");
            
    }//GEN-LAST:event_BlimpiarActionPerformed

    private void BmultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmultiActionPerformed
        Gas objeto = new Gas();
    objeto.capturar(Num1, Num2);
    Num1 = Double.parseDouble(Tnum1.getText());
    Num2 = Double.parseDouble(Tnum2.getText());
    
    double multi= objeto.multi(Num1,Num2);
    TResultado.setText(String.valueOf(multi));
    
    }//GEN-LAST:event_BmultiActionPerformed

    private void Bdivi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bdivi1ActionPerformed
        Gas objeto = new Gas();
    objeto.capturar(Num1, Num2);
    Num1 = Double.parseDouble(Tnum1.getText());
    Num2 = Double.parseDouble(Tnum2.getText());
    
    double divi = objeto.dividir(Num1,Num2);
    TResultado.setText(String.valueOf(divi));

    }//GEN-LAST:event_Bdivi1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulariogas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulariogas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulariogas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulariogas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulariogas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bdivi1;
    private javax.swing.JButton Blimpiar;
    private javax.swing.JButton Bmulti;
    private javax.swing.JButton Bresta;
    private javax.swing.JButton Bsuma;
    private javax.swing.JLabel TResultado;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JLabel Titulo2;
    private javax.swing.JTextField Tnum1;
    private javax.swing.JTextField Tnum2;
    // End of variables declaration//GEN-END:variables
}
